/**
 * Generate the core SW lifecycle handlers (install, activate).
 */
export function generateSwCore(cacheNames: string[]): string {
  const cacheNamesList = cacheNames.map(n => `'${n}'`).join(', ')

  return `// Generated by pwa-lib — do not edit manually
const CACHE_VERSION = 'v${Date.now()}';
const KNOWN_CACHES = [${cacheNamesList}];

self.addEventListener('install', (event) => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(
        keys
          .filter(key => !KNOWN_CACHES.includes(key) && key !== PRECACHE_NAME)
          .map(key => caches.delete(key))
      )
    ).then(() => self.clients.claim())
  );
});
`
}
